version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "infra_test"
  import_paths = ["infra_test"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

