timeout: 300s
queueTtl: 300s

options:
  env:
    - AWS_REGION=us-east-1

steps:

  - id: terraform-version
    name: hashicorp/terraform:0.12.28
    args:
      - version
    timeout: 60s

  - id: terraform-init
    name: hashicorp/terraform:0.12.28
    args:
      - init
      - -backend=false
    waitFor: ['-']
    timeout: 60s

  - id: terraform-validate
    name: hashicorp/terraform:0.12.28
    args:
      - validate
      - -json
      - -no-color
    waitFor:
      - terraform-init
    timeout: 60s

  - id: terraform-format
    name: hashicorp/terraform:0.12.28
    args:
      - fmt
      - -check
    waitFor:
      - terraform-init
    timeout: 60s

  - id: terraform-validate-latest
    name: hashicorp/terraform:latest
    args:
      - validate
      - -json
      - -no-color
    waitFor:
      - terraform-validate
    timeout: 60s

  - id: terraform-validate-zero
    name: hashicorp/terraform:0.12.0
    args:
      - validate
      - -json
      - -no-color
    waitFor:
      - terraform-validate
    timeout: 60s

  - id: policy-parse
    name: instrumenta/conftest
    waitFor:
      - terraform-validate
    entrypoint: '/bin/sh'
    args: [ '-c', "conftest parse *.tf --combine --no-color >| .conftest/module.json" ]

  - id: policy-test
    name: instrumenta/conftest
    waitFor:
      - policy-parse
    entrypoint: '/bin/sh'
    args: [ '-c', "conftest test --no-color --combine --output=tap --policy .conftest/module.rego *.tf" ]
