name: Lint PR

on:
  push:
    #tags:
    #  - v*
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:

  # Check terratest go code
  lint-terratest:
    name: Lint PR - Terratest
    runs-on: ubuntu-latest
    steps:

      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.1
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          working-directory: .terratest

  # Check terraform syntax and formatting
  lint-terraform:
    name: Lint PR - Terraform
    runs-on: ubuntu-latest

    strategy:
      matrix:
        terraform:
          - 0.12.28
          - latest
          - 0.12.0
    steps:

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform }}

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Teraform Validate
        env:
          AWS_REGION: us-east-1
        run: terraform validate -json -no-color

      - name: Terraform Format
        run: terraform fmt -check
